server:
  port: 8081
spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aston
    username: postgres
    password: sa
    poolSize: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
exception:
  handler:
    enabled: true