server:
  port: 8080
spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aston
    username: postgres
    password: sa
    poolSize: 10
  cache:
    capacity: 10
    algorithm: LRUCache
  liquibase:
    change-log: classpath:db/db.changelog-master.yml
    enabled: true
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
exception:
  handler:
    enabled: true
